In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[10, 15]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[27, 14], [10, 15], [4, 23], [9, 10, 29], [26, 24, 19], [8, 14], [14, 24, 2], [18, 3], [18, 14], [20, 21]]


In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[27 14  0  0]
 [10 15  0  0]
 [ 4 23  0  0]
 [ 9 10 29  0]
 [26 24 19  0]
 [ 8 14  0  0]
 [14 24  2  0]
 [18  3  0  0]
 [18 14  0  0]
 [20 21  0  0]]


In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.fit(X, y, epochs=50, verbose=0)

In [9]:
weights = model.get_layer('embedding').get_weights()[0]

In [10]:
weights.shape

(30, 5)

In [14]:
weights[27]

array([ 0.01936182,  0.00695543,  0.07908292,  0.10063598, -0.08173092],
      dtype=float32)

In [18]:
weights[18]

array([-0.01377654, -0.03491215, -0.05224521, -0.02707224,  0.02950971],
      dtype=float32)

In [19]:
weights[14]

array([-0.06556453,  0.09568612,  0.0001562 , -0.07452843,  0.05994178],
      dtype=float32)